openapi: 3.0.3
info:
  title: Mail4GPT API
  version: 1.0.0
  description: Connect ChatGPT with your mail
paths:
  /last_unseen_email:
    post:
      operationId: last_unseen_email_create
      tags:
      - last_unseen_email
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Email'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Email'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Email'
        required: true
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Email'
          description: ''
  /send_email:
    post:
      operationId: send_email_create
      parameters:
      - in: query
        name: body
        schema:
          type: string
        description: Email content
        required: true
      - in: query
        name: subject
        schema:
          type: string
        description: Email subject
        required: true
      - in: query
        name: to
        schema:
          type: string
          format: email
        description: Address to which email will be sent
        required: true
      tags:
      - send_email
      security:
      - tokenAuth: []
      responses:
        '200':
          description: No response body
components:
  schemas:
    Email:
      type: object
      properties:
        from_email:
          type: string
          format: email
        date:
          type: string
          format: date-time
        content:
          type: string
      required:
      - content
      - date
      - from_email
  securitySchemes:
    tokenAuth:
      type: apiKey
      in: header
      name: Authorization
      description: Token-based authentication with required prefix "Token"
